name: animated_toggle_switch
description: Fully customizable, draggable and animated switch with multiple choices and smooth loading animation. It has prebuilt constructors for rolling and size animations.
version: 0.8.0-beta.0
repository: https://github.com/SplashByte/animated_toggle_switch
issue_tracker: https://github.com/SplashByte/animated_toggle_switch/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:

funding:
  - https://buymeacoffee.com/splashbyte
  - https://ko-fi.com/splashbyte

screenshots:
  - description: 'This image shows three example usages of AnimatedToggleSwitch.rolling().'
    path: screenshots/preview.webp
