name: animated_toggle_switch
description: Simple and animated switch with multiple choices and smooth loading animation. It's a good alternative if you don't want to use something like a dropdown menu.
version: 0.7.0
repository: https://github.com/SplashByte/animated_toggle_switch
issue_tracker: https://github.com/SplashByte/animated_toggle_switch/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

funding:
  - https://buymeacoffee.com/splashbyte
  - https://ko-fi.com/splashbyte

screenshots:
  - description: 'This image shows three example usages of AnimatedToggleSwitch.rolling().'
    path: screenshots/preview.webp
